### ISSUE TITLE
As.promise onError not working as intended?

### ISSUE THREAD

**Issue by pschyska** [Matechs-Garage/effect-ts#460]
First of all, thanks for the great package!

I'm trying to build something from the [react example](https://github.com/Matechs-Garage/effect-ts-react), but I'm facing some issues with As.promise. I'm trying to map rejections to some Error type, and the type inference tells me that the Failure case can only contain my type afterwards. However, the actual rejections bubble up and when I match the Exit on Failure<my error type>, it contains a TypeError (that was thrown from Browser fetch originally) and not my error type.

I've added a [test case](https://github.com/pschyska/effect-ts/commit/b3f6ae1e015866b3f0df385776b54beaf739f1aa) that shows the problem. The inferred type here is `As.Exit<string,never>` as expected, but the contained value is actually `Error("err")` or `rejected` and not `mapped u`.

Am I holding it wrong?

Cheers

**Comment by mikearnaldi** [comment]
Thanks for the PR indeed it was a mistake from the last refactor to initial encoding!
